theme: jekyll-theme-pixyll
# title: downlens
# description: Simple automation of PaperMC servers for Windows 10
# logo: [Location of the logo]
# show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
